### ISSUE TITLE
New updates – cross reference with Avocode

### ISSUE THREAD

**Issue by richardbaker** [bakerwilcox/indigofx.co.uk#10]
## General 
- [x] All buttons should have rounded ends and be a single action colour
- [x] Add telephone icon next to phone number and email icon next to email
- [x] Reduce space at the top and bottom of each horizontal block
- [x] Remove Currency Converters on all sub pages and replace with an image
- [x] Remove phone and email banner from all sub pages
- [x] Add simple icons to the circles across the site
- [x] Make top section with converter dark blue across the site
- [x] Introduce a light Indigo colour instead of the grey for the blocks
- [x] Light indigo colour behind for Client Area background block
- [x] Use alternative iPad and iPhone image (black)

## Home Page
- [x] Large image to bleed under the navigation bar to the top of the page
- [x] Logo to be white out text along with nav items on home page
- [x] Make home page fit on screen without vertical scrolling
- [x] Reduce the space between the 3 main texts and the buttons below

## About Us
- [x] Add Security of funds block on this page

## Partnership
- [x] Add application form (downloadable .pdf)

## Open an Account
- [x] Existing terms for the site should be the terms for the application (see terms-application.html for ones to use here)

## Contact Us
- [x] Move google map so that it is positioned better
- [x] Remove italics for address and email address and make normal font

## New Page
- [x] Currency Pairs available – layout on Avocode shortly

**Comment by zanona** [comment]
hi @richardbaker,
Just coming back with a few questions regarding the issues:

1. Add simple icons to the circles across the site
  
  > I will be waiting for the icons. To make it easier, you can pick any icon from this page http://fontawesome.io/icons/ and just let me know their names and where they go.

2. Why Indigo? Page – Add Security of funds block on this page

  > I'm afraid I can't see this new block on the updated design?

3. Partnerships Page – Add application form (downloadable .pdf)

  > Please provide the pdf file

4. Light indigo colour behind for Client Area background block /Use alternative iPad and iPhone image (black)

  > Could you provide the image with transparent background so we can use a different background colour on the module? The PSD contains the image with white background.

5. Open Account Page – Existing terms for the site should be the terms for the application (see terms-application.html for ones to use here)

  > I am not sure I understand how this is supposed to be displayed? Is only a link to the page ok?

Thanks Richard

**Comment by zanona** [comment]
hey @richardbaker, all ready ;)
