### ISSUE TITLE
Additional Request from Indigo

### ISSUE THREAD

**Issue by richardbaker** [bakerwilcox/indigofx.co.uk#5]
Additional Form Fields Requested
Just had a meeting with our compliance department.
We are going to require some additional fields on our registration form. Ideally with drop down options for the band width the client falls under.
 
AVERAGE TRADE SIZE-
ANNUAL VOLUME-
MAXIMUM TRADE SIZE-

**Comment by zanona** [comment]
Hi Richard,
Do we already have the dropdown options available for these fields?
Thank you

**Comment by richardbaker** [comment]
Morning Marcos, I've just sent them an email asking for those. I'll update here shortly.
